spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true

web-crawler:
  host-info: ${CMS_HOST}
  post-contents-limit-count: ${POST_LIMIT:10}
