spring:
  output:
    ansi:
      enabled: never
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  flyway:
    enabled: false

web-crawler:
  host-info:
    url: ${post-host-info.url}          # sample: http://xxxx.com
    port: ${post-host-info.port}        # sample: 80 8080
    login-id: ${post-host-info.userId}
    login-pw: ${post-host-info.userPW}
    post-contents-limit-count: 10